version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    command: 'npm run debug'
    ports:
      - 9229:9229
    volumes:
      - /app/node_modules
      - ./api:/app
